name: Manual Trigger Pipeline

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deployment environment'
        required: false
        default: 'dev'
      version:
        description: 'Deployment version'
        required: true

jobs:
  run-manual-steps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Print Input Values
      run: |
        echo "Selected Environment: ${{ github.event.inputs.environment }}"
        echo "Selected Version: ${{ github.event.inputs.version }}"
